name: "OZ - Tools"
main: de.omegazirkel.risingworld.OZTools
version: 0.23.6
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "This Plugin is providing useful stuff for other Plugins"
license: N/A
website: https://api.github.com/repos/Devidian/rw-plugin-oz-tools/releases/latest
loadorder: -999
